import Footer from '@/components/bonsai/footer/Footer'
import Header from '@/components/bonsai/Header'
import Plans from '@/components/bonsai/Plans'
import Head from 'next/head'
import React, { useEffect } from 'react'

type Props = {}

function Index({}: Props) {
  return (
    <div className="relative border bg-[#fff] w-screen overflow-hidden">
      <Head>
        <title>Ex Bonsai</title>
        <meta name="description" content="Generated by create ex bonsai app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <section>
          <div className=" absolute rounded-3xl -top-[43%]  -right-[19%]  md:right-[3%] -rotate-[20deg] w-[90%] h-[65%] bg-[#f2faff] overflow-hidden"></div>
          <Plans />
        </section>
      </main>

      <Footer />
    </div>
  )
}

export default Index
