import Footer from '@/components/bonsai/Footer'
import Header from '@/components/bonsai/Header'
import Plans from '@/components/bonsai/Plans'
import Head from 'next/head'
import React from 'react'

type Props = {}

function Index({}: Props) {
  return (
    <div className="relative border bg-[#fff] w-full overflow-x-hidden">
      <Head>
        <title>Ex Bonsai</title>
        <meta name="description" content="Generated by create ex bonsai app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <section>
          <div className="absolute rounded-3xl -top-[43%]  -right-[65%]  md:-right-[1%] -rotate-[25deg] w-[90%] h-[72%] bg-[#f2faff] "></div>
          <Plans />
        </section>
      </main>

      <Footer />
    </div>
  )
}

export default Index
