import React from 'react'
import Head from 'next/head'
import Header from '@/components/Instrument/Header'

function Index() {
  return (
    <div className="relative  w-screen h-[140vh] overflow-hidden bg-[#000]">
      <Head>
        <title>Ex Instrument</title>
        <meta name="description" content="Generated by create ex bonsai app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="">
        <section className="flex flex-col space-y-40">
          <p>xx</p>
          <p>xx</p>
          <p>xx</p>
          <p>xx</p>
          <p>xx</p>
        </section>
      </main>
    </div>
  )
}

export default Index
